### PR TITLE
Add support for the thiscall ABI

### PR DESCRIPTION
**Pull request by liranringel**
Fixes https://github.com/rust-lang-nursery/rust-bindgen/issues/541

The thiscall ABI is experimental, so in order to use it nightly is required and also the following statement:
`#![feature(abi_thiscall)]`
That's a problem because the `tests_expectations` crate (in the tests folder) tries to compile it (and stable is required).

### CODE REVIEW

**Comment by pepyakin** [comment]
Hello @liranringel ! Thanks for your PR!

Unfortunately, we don't have nightly tests at the moment. But I believe that we should start to run them eventually. For example we have [`const_fn`](https://github.com/rust-lang-nursery/rust-bindgen/blob/745d60610ec6979368fc240472f7c04a3e04f282/src/features.rs#L154) but we don't test it yet! And there are [a few more features](https://github.com/rust-lang/rust/issues/33626) that we might want to emit in nightly.

I'm not sure what is the best possible way here. 
@fitzgen maybe it is OK to land this without tests?

**Comment by fitzgen** [comment]
For now, it is OK to land this without tests in CI, so long as the emitted bindings contain things that we can look at if/when the emitted bindings change in the future and verify that the changes look right or wrong manually. For this PR concretely, that would be the `extern "fastcall" { ... }` bit in the new expectations file.

Eventually, we should be running rustc nightly tests in CI. I don't want to combinatorially explode our CI test jobs more than we already have, so let's not run all of our many test jobs in both stable and nightly. Instead, I think it makes sense to have just one more CI job that does expectations tests in nightly (since non-nightly can be used to verify that generated bindings aren't changing, and we just need nightly for compiling code with nightly features).

------------------------

When I said "For now, it is OK to land this without tests,"  I intentionally qualified that with "in CI." We *can* land tests that don't run in CI yet, but exist and can run locally:

* Add a new `nightly` feature to `tests/expectations/Cargo.toml`
* Add `--raw-line '#![cfg(feature = "nightly")]'` to the `// bindgen-flags` in the new test header introduced in this PR

Then, running

```
$ cd tests/expectations
$ cargo test --features nightly
```

*should* run this test locally!

When we eventually add nightly CI, we can make it use the same feature.

---------------------

Ok, looking at the PR now :)

**Comment by liranringel** [comment]
@fitzgen thanks for the comprehensive explanation.
How could I make the expectation file that has the `cfg` option to enable the `thiscall` ABI? It's just generated by bindgen, isn't it?

**Comment by fitzgen** [comment]
> How could I make the expectation file that has the cfg option to enable the thiscall ABI? It's just generated by bindgen, isn't it?

This is what the `--raw-line` flags I mentioned are for: they pass the given contents directly though, into the generated bindings, so we can add the `cfg`s that way.

> * Add `--raw-line '#![cfg(feature = "nightly")]'` to the `// bindgen-flags` in the new test header introduced in this PR
> * Add `--raw-line '#![cfg(feature(abi_thiscall))]'` as well

Make sense?

**Comment by liranringel** [comment]
Yes, you may check it.

**Pull request merged**
