### PR TITLE
Fix test expectations

### PR DESCRIPTION
**Pull request by fitzgen**
r? @photoszzt

cc @tmfink: I had to revert the target features commit because there were a bunch of compilation failures in the test expectations (we had another, earlier regression that accidentally made it so that we weren't compiling and running the test expectations in CI, so we didn't catch the target features PR's regressions).

### CODE REVIEW

**Comment by photoszzt** [comment]
@bors-servo  r+

Thanks!

**Comment by tmfink** [comment]
@fitzgen, what are next steps? Should I open another pull request?

What regressions did I introduce? I did not observe any test failures locally.

**Comment by photoszzt** [comment]
@tmfink  Have you tried to run the following: 
cd rust-bindgen/tests/expectations
cargo test

**Comment by fitzgen** [comment]
@tmfink,

Yes, let's open a new pull request to reland it.

As @photoszzt points out, because the test expectations changed, we need to retest that they can still compile, and that their layout unit tests still pass. This is done by changing into the `tests/expectations` directory and running `cargo test`.

I haven't dug into why the test expectations are failing to compile, yet, and I don't have time at the moment. I can help out on Tuesday, though (or answer questions you ask in the new PR before then at that time).

Good luck!

**Comment by photoszzt** [comment]
@fitzgen I think running cargo test in tests/expectations should be documented somewhere. At least I don't know about it until you told me.

**Comment by fitzgen** [comment]
Yeah definitely... I thought we had something in `CONTRIBUTING.md`...

**Comment by tmfink** [comment]
@photoszzt @fitzgen, I always ran `cargo test` from the repo root, which appeared to work.

**Comment by tmfink** [comment]
I see that running `cargo test` from the root is different than running from `tests/expectations`.

**Pull request merged**
