### PR TITLE
WIP: Quote 0.6

### PR DESCRIPTION
**Pull request by Eijebong**
Unsure what I should do about `#[doc]` :/ Should I add a pass that replaces it back with `///` ?

CC @SimonSapin

### CODE REVIEW

**Comment by emilio** [comment]
Doesn't this break #1308 as well?

**Comment by Eijebong** [comment]
Why ? Because of the `Term` abuse ? Seems to work fine with `TokenStream::from_str`

**Comment by emilio** [comment]
Can we use it for doc comments? Or does it eat them instead?

**Comment by Eijebong** [comment]
I've already tried that :p It's transforming them into `#[doc=""]`

**Pull request closed without merging**
