### PR TITLE
Ensure all derive analyses check array limit on bitfields

### LINKED ISSUE #982: Large bitfield causes compilation failures re: derive(Debug)
### Input C/C++ Header

```C++
struct {
  unsigned : 632;
} a;
```

### Bindgen Invocation

```
$ bindgen input.h
```

### Actual Results

```
clang-4.0: warning: treating 'c-header' input as 'c++-header' when in C++ mode, this behavior is deprecated [-Wdeprecated]
abc.h:2:12: warning: width of anonymous bit-field (632 bits) exceeds width of its type; value will be truncated to 32 bits [-Wbitfield-width]
  unsigned : 632;
           ^
1 warning generated.
abc.h:2:12: warning: width of anonymous bit-field (632 bits) exceeds width of its type; value will be truncated to 32 bits [-Wbitfield-width], err: false
ERROR:bindgen::codegen::struct_layout: Calculated wrong layout for _bindgen_ty_1, too more 48 bytes
error[E0277]: the trait bound `[u8; 128]: std::fmt::Debug` is not satisfied
 --> /tmp/bindings-UWtj35.rs:3:75
  |
3 | # [ repr ( C ) ] # [ derive ( Debug , Copy ) ] pub struct _bindgen_ty_1 { pub _bitfield_1 : [ u8 ; 128usize ] , pub __bindgen_align : [ u64 ; 0usize ] , } # [ test ] fn bindgen_test_layout__bindgen_ty_1 ( ) { assert_eq ! ( :: std :: mem :: size_of :: < _bindgen_ty_1 > ( ) , 80usize , concat ! ( "Size of: " , stringify ! ( _bindgen_ty_1 ) ) ) ; assert_eq ! ( :: std :: mem :: align_of :: < _bindgen_ty_1 > ( ) , 8usize , concat ! ( "Alignment of " , stringify ! ( _bindgen_ty_1 ) ) ) ; } impl Clone for _bindgen_ty_1 { fn clone ( & self ) -> Self { * self } } extern "C" {
  |                                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `[u8; 128]` cannot be formatted using `:?`; if it is defined in your crate, add `#[derive(Debug)]` or manually implement it
  |
  = help: the trait `std::fmt::Debug` is not implemented for `[u8; 128]`
  = note: required because of the requirements on the impl of `std::fmt::Debug` for `&[u8; 128]`
  = note: required for the cast to the object type `std::fmt::Debug`

error: aborting due to previous error

Interesting: bindgen emitted Rust code that won't compile!
```

### Expected Results

We shouldn't `derive(Debug)` when a bitfield's allocation unit cannot derive debug.

-------------------------------------------------------

Our various `derive` analyses need to check if any bitfield allocation units are too large to `derive` traits. We compute bitfield allocation units before the `derive` analyses, so this shouldn't be very difficult.

Here is where we keep the `Layout` for a bitfield allocation unit: https://github.com/rust-lang-nursery/rust-bindgen/blob/master/src/ir/comp.rs#L138

https://github.com/rust-lang-nursery/rust-bindgen/blob/master/src/ir/analysis/derive_debug.rs#L270 is where we need to check that (and similar places for the other `derive` analyses).

Happy to mentor anyone who wants to pick this up!

### PR DESCRIPTION
**Pull request by aeleos**
Fixes #982 

r? @fitzgen

### CODE REVIEW

**Comment by fitzgen** [comment]
Looks like CI is complaining because of compilation errors:

```
error[E0425]: cannot find value `RUST_DERIVE_IN_ARRAY_LIMIT` in this scope
   --> /home/travis/build/rust-lang-nursery/rust-bindgen/src/ir/analysis/derive_copy.rs:269:53
    |
269 |                             if bfu.layout().align > RUST_DERIVE_IN_ARRAY_LIMIT {
    |                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in this scope
    |
```

**Comment by fitzgen** [comment]
These changes look like how I'd expect, but we need to add the test case from the original bug report as well.

See https://github.com/rust-lang-nursery/rust-bindgen/blob/master/CONTRIBUTING.md#authoring-new-tests for information on how to add new tests to the test suite.

**Comment by aeleos** [comment]
Ah alright, I'll add that hopefully tonight

**Comment by aeleos** [comment]
Some tests seem to be failing because of this error
```
#![allow(dead_code, non_snake_case, non_camel_case_types, non_upper_case_globals)]


#[repr(C)]
pub struct _bindgen_ty_1 {
    pub _bitfield_1: [u8; 128usize],
    pub __bindgen_align: [u64; 0usize],
}
#[test]
fn bindgen_test_layout__bindgen_ty_1() {
    assert_eq!(
        ::std::mem::size_of::<_bindgen_ty_1>(),
        80usize,
        concat!("Size of: ", stringify!(_bindgen_ty_1))
    );
    assert_eq!(
        ::std::mem::align_of::<_bindgen_ty_1>(),
        8usize,
        concat!("Alignment of ", stringify!(_bindgen_ty_1))
    );
}
impl Default for _bindgen_ty_1 {
    fn default() -> Self {
        unsafe { ::std::mem::zeroed() }
    }
}
extern "C" {
    #[link_name = "a"]
    pub static mut a: _bindgen_ty_1;
}
```
I am not sure what could cause this. The error appears if I use the tests/test-one.sh script, but not if I use cargo test. Any ideas @fitzgen?

**Comment by fitzgen** [comment]
When we generate bindings, we also emit `#[test]`s that assert the size, alignment, and offset of each field for each generated struct. One of these tests is failing. You should be able to reproduce outside of the `test-one.sh` script like this:

```
$ cd tests/expectations
$ cargo test
```

Is this happening in the new test that you added? I wouldn't expect this PR to have a serious impact on the generated bindings for most of our existing test suite, and wouldn't expect any existing tests to start failing their layout tests.

Ok, yeah it looks like this is the nest test. I'm not sure exactly why we are ultimately generating an incorrect layout, and would need to investigate more to figure it out. I expect it involves a bug in how we compute bitfields' physical allocation units.

I think we can land this PR now, however, since it fixes an existing bug, and file a follow up issue for the incorrect layout. In order to land this now, we'll need to add this to the top of the test so that it doesn't generate layout tests for the time being:

```c
// bindgen-flags: --no-layout-tests
```

**Comment by fitzgen** [comment]
@aeleos, BTW, I'm not sure if you're aware that the ["impl period"](https://blog.rust-lang.org/2017/09/18/impl-future-for-rust.html) has just begun, but the folks hacking on `bindgen` during the impl period are hanging out in https://gitter.im/rust-impl-period/WG-dev-tools-bindgen if you want to join us :)

**Comment by aeleos** [comment]
@fitzgen I heard about it but I didn't see the one for bindgen, I'll definitely check it out. Also, I rebased after the recent merge and all the checks passed so it looks like everything is working.

**Comment by fitzgen** [comment]
@bors-servo r+

Thanks @aeleos ! Are you interested in hacking on the follow up issue to this, which is the incorrect layout? I'll file it and include some details in a bit, then drop a link back here. If you want to pick it up, you can tell @highfive :)

**Comment by aeleos** [comment]
@fitzgen Yea I am interested in the incorrect layout issue, it loos like it could be interesting. I'll start looking through the code now and see if I can find anything, but let me know when you have filed the new issue and I'll add myself to it.

**Comment by aeleos** [comment]
@fitzgen It seems like one of the tests broke and froze for some reason. Only one test failed, and it ran for 4 hours with no logs. Have you ever encountered tests failing like this?

**Comment by fitzgen** [comment]
> @fitzgen It seems like one of the tests broke and froze for some reason. Only one test failed, and it ran for 4 hours with no logs. Have you ever encountered tests failing like this?

I restarted it -- I've seen jobs hang before in Travis CI, before it even gets to running the `bindgen` tests. *shrug*

**Pull request merged**
