### PR TITLE
Use Metadata::is_dir

### PR DESCRIPTION
**Pull request by nox**

### CODE REVIEW

**Comment by nox** [comment]
For the record, my use case for this was passing `/dev/null` as the input header, and passing multiple actual headers I care about with `-- -include`.

**Comment by fitzgen** [comment]
> For the record, my use case for this was passing /dev/null as the input header, and passing multiple actual headers I care about with -- -include.

If you pass multiple headers they automatically get `-include`d fwiw.

**Comment by nox** [comment]
It didn't work from command line, but maybe I did it wrong, it was 2am after all. :)

**Comment by fitzgen** [comment]
It may only work with the builder right now.

**Pull request merged**
