### PR TITLE
 codegen: Allow unused_mut to prevent warnings on little-endian machines.

### PR DESCRIPTION
**Pull request by emilio**
And fixup whitespace.

This is a followup #1342.

### CODE REVIEW

**Comment by upsuper** [comment]
It makes me think it would have been better to do something like
```rust
let index = if cfg!(target_endian = "big") {
    bit_width as usize - i
} else {
    i
};
```

**Comment by emilio** [comment]
Yes, but I think `if cfg` is not a built-in anymore... Which makes it not suitable because it'd require adding the dependency to the target.

**Comment by emilio** [comment]
Hmm, I was thinking of https://crates.io/crates/cfg-if, but that's another thing. Sounds good, but we can do it as a followup if you want.

**Comment by emilio** [comment]
Well I guess I may as well fix it here.

**Pull request merged**
