### PR TITLE
Fix license incompatibility

### PR DESCRIPTION
**Pull request by glyn**
Make issue-816.h compatible with bindgen's 3-clause BSD license.

This fixes issue https://github.com/rust-lang-nursery/rust-bindgen/issues/1206.

### CODE REVIEW

**Comment by glyn** [comment]
Looks like the travis failure was not related to this change. Please could somone re-trigger it?

**Comment by emilio** [comment]
Thanks a lot @glyn :)

@bors-servo r+

**Comment by glyn** [comment]
Another unrelated Travis failure.

@bors-servo retry

**Comment by glyn** [comment]
@emilio Just a gentle reminder to investigate the Travis failures which are blocking this PR from merging. Thanks in advance!

**Comment by emilio** [comment]
@bors-servo retry

 * I'm experimenting locally in my repo, but I haven't been able to repro so far.

**Comment by emilio** [comment]
@bors-servo retry

 * Issues should be fixed in #1210

**Comment by emilio** [comment]
> The command "eval curl -sf  -o $CASHER_DIR/bin/casher https://build.travis-ci.org/files/casher " failed. Retrying, 2 of 3.

Looks intermittent...

@bors-servo retry

**Pull request merged**
