### PR TITLE
Add `bindgen::Builder::derive_copy`

### PR DESCRIPTION
**Pull request by mchlrhw**
Fixes https://github.com/rust-lang-nursery/rust-bindgen/issues/948

### CODE REVIEW

**Comment by fitzgen** [comment]
Thanks for the PR @mchlrhw ! The code looks great, but we need a test before we merge this.

Can you add something like this to `tests/headers/do-not-derive-copy.hpp`:

```c++
// bindgen-flags: --no-derive-copy

class WouldBeCopyButWeAreNotDerivingCopy {
    int x;
};
```

And then verify that the generated `tests/expectations/tests/do-not-derive-copy.rs` file doesn't add a `derive(Copy)`.

Thanks again!

**Comment by mchlrhw** [comment]
Cool, thanks for pointing me in the right direction. I wasn't quite sure how testing worked, but your message and `CONTRIBUTING.md` really helped!

**Comment by fitzgen** [comment]
> Cool, thanks for pointing me in the right direction. I wasn't quite sure how testing worked, but your message and CONTRIBUTING.md really helped!

Glad to hear that :)

**Pull request merged**
