### PR TITLE
Add an option to add lines per module.

### LINKED ISSUE #1307: Linking bindgen-generated libraries against other bindgen-generated libraries
If there are two libraries `a.h`:
```c
struct Foo { ... }
```
and `b.h`:
```c
#include "a.h"
Foo bar() { ... }
```
and both of these have `sys` crates generated by bindgen, there should be a way to get `b_sys` to use the `Foo` from `a_sys`. We can almost do this by putting the following into the `build.rs` of `b_sys`:
```rust
   builder.raw_line("use a_sys::*");
```
but this produces:
```rust
use a_sys::*;
pub mod root {
   ...
   fn bar() -> root::Foo { ... }
}
```
That is the `raw_line` is outside the root crate, not inside it. If we could put raw lines inside the root, this would be pretty easy.

### PR DESCRIPTION
**Pull request by emilio**
Fixes #1307

### CODE REVIEW

**Comment by emilio** [comment]
cc @ajeffrey

r? @fitzgen

**Comment by emilio** [comment]
Err, meant to cc @asajeffrey

**Comment by asajeffrey** [comment]
Thanks! Here it is in action... https://github.com/asajeffrey/mozjs/commit/4516ab9abba2403e40079ccd5c688b0d43e8bb04

**Pull request merged**
