### PR TITLE
Derive + blacklisted types

### PR DESCRIPTION
**Pull request by fitzgen**
* [X] document blacklisting + derive interaction
* [X] derive `Copy`
* [X] derive `Debug`
* [X] `--impl-debug`
* [x] derive `Default`
* [x] derive `Hash`
* [x] derive `PartialEq`

### CODE REVIEW

**Comment by upsuper** [comment]
Although bindgen shouldn't put any assumption on blacklisted type, it could potentially be a trouble to ban all the derivation on them as well. (I haven't tried, but `Debug` seems to be relied widely, so it might become a problem.)

Probably we can allow people to specify which blacklisted type can derive what trait.

Maybe I should try this patch first and see if it really becomes a problem.

**Comment by fitzgen** [comment]
This patch works fine with mozjs.

**Comment by fitzgen** [comment]
With Stylo, I get the following error:

```
error: this trait cannot be derived for unions
    --> /home/fitzgen/mozilla-central/obj-x86_64-pc-linux-gnu/toolkit/library/x86_64-unknown-linux-gnu/release/build/style-14c013fa10f9d775/out/gecko/structs_release.rs:3238:22
     |
3238 |             #[derive(Debug, Copy)]
     |                      ^^^^^
```

on this struct:

```rust
            #[repr(C)]
            #[derive(Debug, Copy)]
            pub union OwningNodeOrString_Value {
                pub _bindgen_opaque_blob: [u64; 2usize],
            }
```

But let me double check that against master and see whether or not that same error occurs.

**Comment by fitzgen** [comment]
Hm yeah with master I get tons of "copy could not be implemented for this type".

**Comment by fitzgen** [comment]
Here is a minimal test case:

```rust
// bindgen-flags: --opaque-type DoggoOrNull

class Doggo {};

class None {};

union DoggoOrNull {
    Doggo doggo;
    None none;
};
```

Testing if this is also a bug on master or not.

**Comment by fitzgen** [comment]
It kind of seems to me that we shouldn't be emitting `union`s for opaque unions -- just structs of the right size/align...

**Comment by upsuper** [comment]
You need to make bindgen target 1.0 for building stylo.

**Comment by fitzgen** [comment]
Ok, so I targeted 1.0 and still getting errors that seem unrelated to deriving:

```
error[E0432]: unresolved import `gecko_bindings::structs::ServoStyleSheet`
  --> /home/fitzgen/mozilla-central/servo/components/style/gecko/data.rs:10:77
   |
10 | use gecko_bindings::structs::{RawGeckoPresContextOwned, ServoStyleSetSizes, ServoStyleSheet};
   |                                                                             ^^^^^^^^^^^^^^^ no `ServoStyleSheet` in `gecko_bindings::structs`. Did you mean to use `ServoStyleContext`?
```

But I verified that `root::mozilla::ServoStyleSheet` *is* defined in the `structs_*.rs` bindings. Did it not used to be namespaced or something?

Anyways, I don't think these errors are related to this PR, and it fixes other errors that get hit when trying to build Stylo with master (the copy deriving) so I think we should land this.

**Pull request merged**
