### PR TITLE
codegen: expose enum variant documentation.

### LINKED ISSUE #1250: Generated bindings don't transfer doxygen documentation comments for enum variants
### Used software versions

bindgen: v0.32.3
llvm/clang: 5.0.1

### Input C/C++ Header

```C++

/** Document enum */
enum B {
    /// Document field with three slashes
    VAR_A = 0,
    /** Document field with preceeding star */
    VAR_B = 1,
    /*! Document field with preceeding exclamation */
    VAR_C = 2,
    VAR_D = 3, /**< Document field with following star */
    VAR_E = 4, /*!< Document field with following exclamation */
};
```

### Bindgen Invocation

```rust
    let bindings = bindgen::Builder::default()
        .header("input.h")
        .layout_tests(false)
        .generate().unwrap();
```

Also same with any of `.constified_enum(".*")`/`.rustified_enum(".*")`/`.bitfield_enum(".*")`/`.prepend_enum_name("false")`.

### Actual Results

```rust
pub const B_VAR_A: B = 0;
pub const B_VAR_B: B = 1;
pub const B_VAR_C: B = 2;
pub const B_VAR_D: B = 3;
pub const B_VAR_E: B = 4;
pub type B = u32;
```

### Expected Results

Generated enum constants and, when possible, enum type itself, should have the documentation comments, just like it is now done for struct.

### PR DESCRIPTION
**Pull request by emilio**
Fixes #1250.

### CODE REVIEW

**Comment by pepyakin** [comment]
r=me modulo the travis error

**Comment by pepyakin** [comment]
seems like all ok, @bors-servo r+

Thanks!

**Comment by emilio** [comment]
Yeah, travis timed out, but the PR push is green...

**Comment by emilio** [comment]
Thanks for the review!

**Pull request merged**
