### PR TITLE
(WIP) Setup Appveyor

### PR DESCRIPTION
**Pull request by UK992**
CC @upsuper @emilio 

Issues:
- `test/expectations` fails at:
```
error[E0512]: transmute called with differently sized types: u64 (64 bits) to i32 (32 bits)
  --> tests\bitfield_align_2.rs:78:18
   |
78 |         unsafe { ::std::mem::transmute(val as u64) }
   |                  ^^^^^^^^^^^^^^^^^^^^^ transmuting between 64 bits and 32 bits
```
- MSVC with LLVM 3.9: many tests fails
- 32-bit builds: many tests fails

Appveyor build: https://ci.appveyor.com/project/UK992/rust-bindgen/build/1.0.62

### CODE REVIEW

**Comment by upsuper** [comment]
Hmmm... I wasn't aware of tests inside tests/expectations... and yeah, it fails for the same reason locally, will investigate.

32bit builds seem to be much broken at present...

Should we probably merge this and fix the failures latter?

**Comment by fitzgen** [comment]
A lot of the test scripts seems like copy/paste of functionality we have in existing scripts. Is the reason they can't be shared because the existing scripts are bash? If so, we should file a follow up to port them all to python or something. I'd really like to avoid duplicating them, as it will make changing them much more difficult.

> Should we probably merge this and fix the failures latter?

Ideally mark them as "allow failures" somehow, and then when we fix them, remove that annotation. Does appveyor allow this kind of thing?

**Comment by fitzgen** [comment]
@UK992 would you mind rebasing and squashing this PR? Then we can land it and address the above concerns as follow ups.

**Comment by fitzgen** [comment]
/me grumbles that appveyor's results are impossible to read if one is red-green colorblind

**Comment by UK992** [comment]
done.

**Comment by fitzgen** [comment]
Thanks @UK992! Very appreciated :)

**Pull request merged**
