### PR TITLE
ir: Handle *const T at the codegen level.

### PR DESCRIPTION
**Pull request by emilio**
Followup to #1311.

### CODE REVIEW

**Comment by emilio** [comment]
I had a feeling this may fix some odd cases of mixing const and non-const pointer... Since you insisted it I found a test-case and I just added it :)

@bors-servo r=fitzgen

**Comment by cynecx** [comment]
Thanks for all the effort! However, I am wondering when we can expect a version bump with the recent changes. https://github.com/sodiumoxide/sodiumoxide/pull/208 is actually waiting for an upstream release with these changes.

**Comment by emilio** [comment]
Hi! Just published v0.37.0. Thank you!

**Pull request merged**
