### PR TITLE
TemplateParameters do not return Option

### LINKED ISSUE #960: TemplateParameters' methods should just return a Vec, not an Option<Vec>
I thought that the `Option` would be useful, but in practice we do pretty much ignore that it is an option and do things like `params.unwrap_or(vec![])`. And then in other places when the result is `Some` we assume that the contained `Vec` is not empty, when that isn't always the case.

It will be much simpler to just return a `Vec` that is either empty or not.

And also `usize` instead of `Option<usize>` for `num_self_template_params`.

The trait's comment will need to be updated as well.

https://github.com/rust-lang-nursery/rust-bindgen/blob/cd41e5cfe26555af574e81b6aa3bed2b84a18000/src/ir/template.rs#L102

### PR DESCRIPTION
**Pull request by tamird**
Fixes #960.
Closes #1245.

I found it useful to do this incrementally, changing each method in a separate commit and ensuring the tests continue to pass unchanged.

r? @emilio 
/cc @ericho

### CODE REVIEW

**Comment by tamird** [comment]
Rebased.

**Comment by ericho** [comment]
No problem @emilio I was stuck anyway.

This is great I can learn from @tamird changes :smile:

**Comment by tamird** [comment]
@emilio could I get another r+?

**Comment by emilio** [comment]
@bors-servo r+

Sure, thanks both!

**Comment by tamird** [comment]
I bisected this down to the last commit - the others all pass. @emilio any ideas?
```
--- stderr
cpp/Test.h:1:9: warning: #pragma once in main file [-Wpragma-once-outside-header], err: false
thread 'main' panicked at '"::" is not a valid Term', /Users/tamird/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-0.3.6/src/stable.rs:463:9
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at libstd/sys_common/backtrace.rs:59
             at libstd/panicking.rs:380
   3: std::panicking::default_hook
             at libstd/panicking.rs:396
   4: std::panicking::begin_panic
             at libstd/panicking.rs:576
   5: std::panicking::begin_panic
             at libstd/panicking.rs:537
   6: std::panicking::try::do_call
             at libstd/panicking.rs:521
   7: proc_macro2::imp::validate_term
             at /Users/tamird/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-0.3.6/src/stable.rs:463
   8: proc_macro2::imp::Term::new
             at /Users/tamird/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-0.3.6/src/stable.rs:406
   9: proc_macro2::Term::_new
             at /Users/tamird/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-0.3.6/src/lib.rs:424
  10: bindgen::codegen::root_import
             at /Users/tamird/src/rust-bindgen/src/codegen/mod.rs:78
  11: <bindgen::ir::module::Module as bindgen::codegen::CodeGenerator>::codegen::{{closure}}
             at /Users/tamird/src/rust-bindgen/src/codegen/mod.rs:424
  12: bindgen::codegen::CodegenResult::inner
             at /Users/tamird/src/rust-bindgen/src/codegen/mod.rs:212
  13: alloc::str::<impl alloc::slice::SliceConcatExt<str> for [S]>::concat::{{closure}}
             at /Users/tamird/src/rust-bindgen/src/codegen/mod.rs:423
  14: <std::ffi::c_str::CString as core::ops::deref::Deref>::deref
             at /Users/tamird/src/rust-bindgen/src/codegen/mod.rs:360
  15: bindgen::codegen::codegen::{{closure}}
             at /Users/tamird/src/rust-bindgen/src/codegen/mod.rs:3441
  16: bindgen::ir::context::BindgenContext::gen
             at /Users/tamird/src/rust-bindgen/src/ir/context.rs:1222
  17: bindgen::codegen::codegen
             at /Users/tamird/src/rust-bindgen/src/codegen/mod.rs:3419
  18: bindgen::Bindings::generate
             at /Users/tamird/src/rust-bindgen/src/lib.rs:1605
  19: core::ptr::<impl *const T>::offset
             at /Users/tamird/src/rust-bindgen/src/lib.rs:1072
  20: build_script_build::main
             at ./build.rs:36
  21: std::rt::lang_start::{{closure}}
             at /Users/travis/build/rust-lang/rust/src/libstd/rt.rs:74
  22: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:479
  23: panic_unwind::dwarf::eh::read_encoded_pointer
             at libpanic_unwind/lib.rs:102
  24: rust_panic
             at libstd/panicking.rs:458
             at libstd/panic.rs:358
             at libstd/rt.rs:58
  25: std::rt::lang_start
             at /Users/travis/build/rust-lang/rust/src/libstd/rt.rs:74
  26: <build_script_build::MacroCallback as core::fmt::Debug>::fmt
```

**Comment by tamird** [comment]
Oops, the first bad commit is the first commit. Did something wrong the first time.

**Comment by tamird** [comment]
@emilio can I get another run, please?

**Comment by emilio** [comment]
Yeah, sorry for the lag. Thanks again!

@bors-servo r+

**Comment by emilio** [comment]
Only one test timed out.

**Pull request merged**
