### PR TITLE
Update lazy_static to 1.0

### PR DESCRIPTION
**Pull request by Eijebong**

### CODE REVIEW

**Comment by fitzgen** [comment]
@bors-servo r+

Thanks!

**Comment by Eijebong** [comment]
Ow, didn't see bindgen shipped a lock file. Should I update it or should we wait for https://github.com/nagisa/rust_libloading/pull/33 to land (to avoid the duplicated dependency) ?

**Comment by fitzgen** [comment]
Let's wait.

**Comment by Eijebong** [comment]
Done :)

**Comment by fitzgen** [comment]
Thanks @Eijebong !

@bors-servo r+

**Pull request merged**
